### ISSUE TITLE
flower: connection refused and can't login

### ISSUE THREAD

**Issue by nareto** [tiangolo/full-stack-fastapi-postgresql#101]
Hi, this project looks incredibily useful, so first of all I'd like to express my gratitude to tiangolo for sharing it.

I'm having trouble running it in docker-machine from Windows 10 (so docker running inside Virtualbox).  To make the backend mount correctly `/app` I changed the volume lines in `docker-compose.dev.volumes.yml` to include the full path in docker-machine virtualbox, i.e. something like `/windowsvolume/pathtocode/backend/app:/app`. This works, if I do `docker exec -it base-project_backend-tests_1 /bin/bash` I can see the app directory. 

However when I try to login on 192.168.99.100 with the username/password present in `cookiecutter-config-file.yml` for "first_superuser" I get a few seconds delay (after I press login) and then a " Incorrect email or password" message. 

In the logs of the flower container I see a bunch of these in a row
```
[E 200118 18:25:34 gen:661] Multiple exceptions in yield list
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 656, in callback
        result_list.append(f.result())
      File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.5/site-packages/celery/app/control.py", line 109, in conf
        return self._request('dump_conf', with_defaults=with_defaults)
      File "/usr/local/lib/python3.5/site-packages/celery/app/control.py", line 71, in _request
        timeout=self.timeout, reply=True,
      File "/usr/local/lib/python3.5/site-packages/celery/app/control.py", line 316, in broadcast
        limit, callback, channel=channel,
      File "/usr/local/lib/python3.5/site-packages/kombu/pidbox.py", line 283, in _broadcast
        chan = channel or self.connection.default_channel
      File "/usr/local/lib/python3.5/site-packages/kombu/connection.py", line 766, in default_channel
        self.connection
      File "/usr/local/lib/python3.5/site-packages/kombu/connection.py", line 751, in connection
        self._connection = self._establish_connection()
      File "/usr/local/lib/python3.5/site-packages/kombu/connection.py", line 706, in _establish_connection
        conn = self.transport.establish_connection()
      File "/usr/local/lib/python3.5/site-packages/kombu/transport/pyamqp.py", line 116, in establish_connection
        conn = self.Connection(**opts)
      File "/usr/local/lib/python3.5/site-packages/amqp/connection.py", line 165, in __init__
        self.transport = self.Transport(host, connect_timeout, ssl)
      File "/usr/local/lib/python3.5/site-packages/amqp/connection.py", line 186, in Transport
        return create_transport(host, connect_timeout, ssl)
      File "/usr/local/lib/python3.5/site-packages/amqp/transport.py", line 299, in create_transport
        return TCPTransport(host, connect_timeout)
      File "/usr/local/lib/python3.5/site-packages/amqp/transport.py", line 95, in __init__
        raise socket.error(last_err)
    OSError: [Errno 111] Connection refused
 
```

followed by this

```
[E 200118 18:25:36 events:123] Failed to capture events: '[Errno 111] Connection refused', trying again in 4 seconds.
[E 200118 18:25:40 events:123] Failed to capture events: '[Errno 111] Connection refused', trying again in 8 seconds.
[E 200118 18:25:48 events:123] Failed to capture events: '[Errno 111] Connection refused', trying again in 16 seconds.
[E 200118 18:26:04 events:123] Failed to capture events: '[Errno 111] Connection refused', trying again in 32 seconds.
[I 200118 18:26:36 mixins:231] Connected to amqp://guest:**@queue:5672//
[E 200118 18:39:07 broker:77] RabbitMQ management API call failed: [Errno 111] Connection refused
[E 200118 18:39:07 broker:78] Make sure RabbitMQ Management Plugin is enabled (rabbitmq-plugins enable rabbitmq_management)
[E 200118 18:39:13 broker:77] RabbitMQ management API call failed: [Errno 111] Connection refused
[E 200118 18:39:13 broker:78] Make sure RabbitMQ Management Plugin is enabled (rabbitmq-plugins enable rabbitmq_management)

```

I am totally unfamiliar with Celery so I'm not sure how to go further there. BTW I can access and login into the flower, traefik and pgadmin UIs, but /docs and /redoc show me the nginx 404 error page.

**Comment by nareto** [comment]
I realised the backend was failing because of a wrong import from pydantic. I got the pull request #100 and it is now.... improved. I can access /docs and login there, but still not on the frontend

**Comment by nareto** [comment]
I'm sorry for all the edits. I just realized that while login is working, I still get the same errors in the flower container as in the first post, so **you may wanna consider reopening this.**

**Comment by dmontagu** [comment]
@nareto Does #37 help at all?

**Comment by nareto** [comment]
@dmontagu with that PR the flower container doesn't throw anymore errors, but again I can't login from the frontend (login from /docs works)

**Comment by tiangolo** [comment]
Thanks for the help here @dmontagu ! :cake: :bowing_man: 

@nareto if you're still having errors, make sure you read the generated README and the logs of your containers, that will probably help you debugging it.
