### ISSUE TITLE
`Internal Server Error` when using `pydantic.validators`

### ISSUE THREAD

**Issue by Toreno96** [tiangolo/full-stack-fastapi-postgresql#114]
Hi,

I customized `app.schemas.user.UserBase` by adding function decorated with the `pydantic.validators` (<https://pydantic-docs.helpmanual.io/usage/validators/>):

```python
class UserBase(BaseModel):
    email: Optional[str] = None
    is_active: Optional[bool] = True
    is_superuser: Optional[bool] = False
    full_name: Optional[str] = None

    @validator("full_name")
    def contains_space(cls, value):
        if " " not in value:
            raise ValueError("must contain a space")
        return value
```

But after sending e.g. such request:

```shell
curl -X POST "http://localhost/api/v1/users/open" \
    -H "accept: application/json" \
    -H "Content-Type: application/json" \
    -d '{"password": "string", "email": "user@example.com", "full_name": "string"}'
```

I get `500 Internal Server Error`.

Full traceback:
```
INFO:     172.19.0.3:56778 - "POST /api/v1/users/open HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 140, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 134, in __call__
    await self.error_middleware(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 178, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 156, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "./app/main.py", line 43, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/usr/local/lib/python3.7/site-packages/starlette_prometheus/middleware.py", line 47, in dispatch
    raise e from None
  File "/usr/local/lib/python3.7/site-packages/starlette_prometheus/middleware.py", line 43, in dispatch
    response = await call_next(request)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 73, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 62, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 590, in __call__
    await route(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 208, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 135, in app
    raw_response = await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.7/site-packages/starlette/concurrency.py", line 25, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./app/api/api_v1/endpoints/users.py", line 118, in create_user_open
    user_in = UserCreate(password=password, email=email, full_name=full_name)
  File "pydantic/main.py", line 283, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for UserCreate
full_name
  must contain a space (type=value_error)
```

It seems FastAPI does not handle it properly in this case.

I also created the simple bare (without using project template) FastAPI app:

```python
from fastapi import FastAPI
from pydantic import BaseModel, EmailStr, validator

app = FastAPI()


class User(BaseModel):
    id: int
    email: EmailStr
    name: str

    @validator("name")
    def contains_space(cls, value):
        if " " not in value:
            raise ValueError("must contain a space")
        return value


@app.post("/users/", response_model=User)
async def create_user(user: User):
    return user
```

```shell
curl -X POST "http://localhost:8000/users/" \
    -H "accept: application/json" \
    -H "Content-Type: application/json" \
    -d '{"id": 0, "email": "user@example.com", "name": "string"}'
```

But there I get expected response, `422 Unprocessable Entity` with the body:

```json
{
  "detail": [
    {
      "loc": [
        "body",
        "user",
        "name"
      ],
      "msg": "must contain a space",
      "type": "value_error"
    }
  ]
}
```

That's way I'm reporting an issue with the full-stack-fastapi-postgresql, not fastapi.

**Comment by tiangolo** [comment]
Thanks for the thorough report! And thanks for trying with bare FastAPI.

I'm pretty sure that's because your backend Dockerfile has an outdated FastAPI version. It will probably work if you update it.

**Comment by Toreno96** [comment]
@tiangolo I updated FastAPI to the most recent version and rebuilt the containers, but the bug still persists.

I can see though that there were a lot of changes to the whole project template, comparing to the version from which I initialized [my project](https://github.com/Toreno96/hello-fastapi), so maybe it is some old bug?

**Comment by tiangolo** [comment]
Thanks for the patience :sweat_smile: 

Yeah, it could be. The best would be to try with a newly generated project, add only that modification, and see if the error persists. If it doesn't, then it was a change from the version you used to start your project and the most recent one.

**Comment by dorinclisu** [comment]
I also get the same behavior with bare fastapi 0.61.2. (It might be appropriate to open issue on https://github.com/tiangolo/fastapi instead but this was my only relevant google search match.)

I don't have any custom exception handlers or any other fancy stuff that might interfere, just a request body model with a custom validator.
