### ISSUE TITLE
frontend fails to build during testing because of permissions error

### ISSUE THREAD

**Issue by wuhland** [tiangolo/full-stack-fastapi-postgresql#196]
Not quite sure what to make of this one. I havent touched the front end yet but have made some changes to the api and went to run tests for the first time when I got this error: 

```
fs.js:114
    throw err;
    ^

Error: EACCES: permission denied, open '/usr/local/lib/node_modules/npm/bin/npm-cli.js'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:20)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c npm run test:unit' returned a non-zero code: 1

```
Wondering if anybody had run into this before.

**Comment by wuhland** [comment]
after running the tests I am gettting permissions error on all containers and none of them can be rebuilt.

**Comment by tiangolo** [comment]
Maybe the container with mounted files generated new files with the `root` user inside the container. You could probably change them to your user.

If you are still having issues, try generating a new project from scratch, following the generated README and making sure that everything works as expected.

And then compare that to your project to see what could have changed.
