### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by jet10000** [tiangolo/full-stack-fastapi-postgresql#25]
-_-!

**Comment by tiangolo** [comment]
Sorry, I can't help you if you don't provide more information.

**Comment by muxuezi** [comment]
So do I.

My app name is `ann`, I can't login from `http://127.0.0.1/login`(vue) aflter I run docker-compose on my macOS. However, other urls can login, include `http://127.0.0.1/docs`, `http://127.0.0.1/redoc`, `http://127.0.0.1:5050`, `http://127.0.0.1:5555`, `http://127.0.0.1:8090/dashboard/`

when I submit loging form at `http://127.0.0.1/login`, my chrome dev console shows as following info:

···
Access to XMLHttpRequest at 'http://localhost/api/v1/login/access-token' from origin 'http://127.0.0.1' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
···

when I run **docker logs -f ann_backend_1** in my terminal:

```bash
Checking for script in /app/prestart.sh
Running script /app/prestart.sh
INFO:__main__:Initializing service
INFO:__main__:Starting call to '__main__.init', this is the 1st time calling it.
ERROR:__main__:(psycopg2.OperationalError) could not connect to server: Connection refused
        Is the server running on host "db" (172.18.0.6) and accepting
        TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/e3q8)
WARNING:__main__:Finished call to '__main__.init' after 0.004(s), this was the 1st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 2nd time calling it.
ERROR:__main__:(psycopg2.OperationalError) could not connect to server: Connection refused
        Is the server running on host "db" (172.18.0.6) and accepting
        TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/e3q8)
WARNING:__main__:Finished call to '__main__.init' after 1.010(s), this was the 2nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 3rd time calling it.
INFO:__main__:Service finished initializing
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> d4867f3a4c0a, First revision
INFO:__main__:Creating initial data
INFO:__main__:Initial data created
INFO: Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
INFO: Started reloader process [1]
INFO: Started server process [10]
INFO: Waiting for application startup.
INFO: ('172.18.0.3', 54674) - "GET /redoc HTTP/1.1" 200
INFO: ('172.18.0.3', 54674) - "GET /api/v1/openapi.json HTTP/1.1" 200
INFO: ('172.18.0.3', 54676) - "GET /api/v1/api/v1/login/access-token HTTP/1.1" 404
INFO: Shutting down
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 368, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/asgi2.py", line 7, in __call__
    await instance(receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 125, in asgi
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 103, in asgi
    await asgi(receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/base.py", line 27, in asgi
    response = await self.dispatch_func(request, self.call_next)
  File "./app/main.py", line 34, in db_session_middleware
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/base.py", line 44, in call_next
    task.result()
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/base.py", line 37, in coro
    await inner(request.receive, queue.put)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 138, in simple_response
    await inner(receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 74, in app
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 63, in app
    await instance(receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in awaitable
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 78, in app
    raw_response = await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.7/site-packages/starlette/concurrency.py", line 24, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./app/api/api_v1/endpoints/login.py", line 34, in login_access_token
  File "./app/crud/user.py", line 23, in authenticate
  File "./app/core/security.py", line 7, in verify_password
  File "/usr/local/lib/python3.7/site-packages/passlib/context.py", line 2342, in verify
    return record.verify(secret, hash, **kwds)
  File "/usr/local/lib/python3.7/site-packages/passlib/utils/handlers.py", line 761, in verify
    return consteq(self._calc_checksum(secret), chk)
  File "/usr/local/lib/python3.7/site-packages/passlib/handlers/bcrypt.py", line 530, in _calc_checksum
    self._stub_requires_backend()
  File "/usr/local/lib/python3.7/site-packages/passlib/utils/handlers.py", line 2221, in _stub_requires_backend
    cls.set_backend()
  File "/usr/local/lib/python3.7/site-packages/passlib/utils/handlers.py", line 2123, in set_backend
    return owner.set_backend(name, dryrun=dryrun)
  File "/usr/local/lib/python3.7/site-packages/passlib/utils/handlers.py", line 2130, in set_backend
    return cls.set_backend(name, dryrun=dryrun)
  File "/usr/local/lib/python3.7/site-packages/passlib/utils/handlers.py", line 2155, in set_backend
    cls._set_backend(name, dryrun)
  File "/usr/local/lib/python3.7/site-packages/passlib/utils/handlers.py", line 2278, in _set_backend
    super(SubclassBackendMixin, cls)._set_backend(name, dryrun)
  File "/usr/local/lib/python3.7/site-packages/passlib/utils/handlers.py", line 2191, in _set_backend
    ok = loader(**kwds)
  File "/usr/local/lib/python3.7/site-packages/passlib/handlers/bcrypt.py", line 551, in _load_backend_mixin
    if _detect_pybcrypt():
  File "/usr/local/lib/python3.7/site-packages/passlib/handlers/bcrypt.py", line 73, in _detect_pybcrypt
    import bcrypt
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1368, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1408, in _fill_cache
OSError: [Errno 107] Transport endpoint is not connected: '.'
Checking for script in /app/prestart.sh
Running script /app/prestart.sh
INFO:__main__:Initializing service
INFO:__main__:Starting call to '__main__.init', this is the 1st time calling it.
INFO:__main__:Service finished initializing
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO:__main__:Creating initial data
INFO:__main__:Initial data created
INFO: Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
INFO: Started reloader process [1]
INFO: Started server process [11]
INFO: Waiting for application startup.
INFO: ('172.18.0.2', 54796) - "POST /api/v1/login/access-token HTTP/1.1" 200
INFO: ('172.18.0.2', 54812) - "POST /api/v1/login/access-token HTTP/1.1" 200
INFO: ('172.18.0.2', 54816) - "GET /api/v1/login/access-token HTTP/1.1" 405
```

**Comment by GetCurious** [comment]
@muxuezi thanks! not sure what are these settings though

**Comment by tiangolo** [comment]
Thanks for the help @muxuezi ! :mage: 

I think we can now close this issue, right @jet10000 ?
