### ISSUE TITLE
UnicodeEncodeError during cookiecutter

### ISSUE THREAD

**Issue by Athius** [tiangolo/full-stack-fastapi-postgresql#301]
Hi everyone,

I have an issue at the end of the configuration (after I set docker_image_frontend value):

```
Traceback (most recent call last):
  File "$HOME/.local/bin/cookiecutter", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "$HOME/.local/lib/python3.8/site-packages/cookiecutter/cli.py", line 140, in main
    cookiecutter(
  File "$HOME/.local/lib/python3.8/site-packages/cookiecutter/main.py", line 101, in cookiecutter
    result = generate_files(
  File "$HOME/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 352, in generate_files
    generate_file(
  File "$HOME/.local/lib/python3.8/site-packages/cookiecutter/generate.py", line 180, in generate_file
    fh.write(rendered_file)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcc3' in position 254: surrogates not allowed
```

Does anyone have the same issue?

My configuration:
Python: 3.8.2
Cookiecutter: 1.7.2
WSL-Ubuntu 20.04.1

Thanks

**Comment by Athius** [comment]
I found the problem: I had only "python3" command and not "python". I fix it by installing python-is-python3

**Comment by tiangolo** [comment]
Thanks for coming to report back and close the issue! 🍰 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
