### ISSUE TITLE
Flower container dies on deploy

### ISSUE THREAD

**Issue by ksdfg** [tiangolo/full-stack-fastapi-postgresql#314]
I made a new repo with cookiecutter, and tried running deploying with docker-compose with no changes. The `flower` container always dies at launch with the following output

```
Traceback (most recent call last):
  File "/usr/local/bin/flower", line 5, in <module>
    from flower.__main__ import main
  File "/usr/local/lib/python3.9/site-packages/flower/__main__.py", line 4, in <module>
    from flower.command import FlowerCommand
  File "/usr/local/lib/python3.9/site-packages/flower/command.py", line 17, in <module>
    from celery.bin.base import Command
ImportError: cannot import name 'Command' from 'celery.bin.base' (/usr/local/lib/python3.9/site-packages/celery/bin/base.py)
```

I am a newbie and not very well versed with a lot of stuff here, but is it an issue with celery version or the flower image being used?

**Comment by ksdfg** [comment]
Changing flower image tag from `latest` to `0.9.5` fixed this for me, all the tests were passing as well

**Comment by YuriiMotov** [comment]
Outdated
