### ISSUE TITLE
Celery lost connection to broker constantly

### ISSUE THREAD

**Issue by duz-sg** [tiangolo/full-stack-fastapi-postgresql#407]
Hi,

My app had an issue several days ago, caused many messages stuck in the queue, after a restart, a new issue occurred, as soon as the consumer receives a message from the broker, the consumer-broker connection will be lost, causing the consumer to unable to ack the broker, also leads to a re-connect to the broker.

The error message is below:
```
[2021-07-28 18:35:56,825: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.8/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.8/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/usr/local/lib/python3.8/site-packages/kombu/asynchronous/hub.py", line 364, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/base.py", line 238, in on_readable
    reader(loop)
  File "/usr/local/lib/python3.8/site-packages/kombu/transport/base.py", line 220, in _read
    drain_events(timeout=0)
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 508, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 514, in blocking_read
    return self.on_inbound_frame(frame)
  File "/usr/local/lib/python3.8/site-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 520, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
  File "/usr/local/lib/python3.8/site-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/usr/local/lib/python3.8/site-packages/amqp/connection.py", line 650, in _on_close
    raise error_for_code(reply_code, reply_text,
amqp.exceptions.InternalError: (0, 0): (541) INTERNAL_ERROR
[2021-07-28 18:36:01,878: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
```

I have debugged for days, tried several workarounds: reset rabbitmq, `celery_app.conf.broker_pool_limit = None`, `celery_app.conf.broker_heartbeat = 0`, change consumer `concurrency=1`, even pruned all docker images and rebuild all of them, but still, the situation persists.

Right now I am suspecting some underlying docker image or library gets updated and caused this.

Any advice on this? Thanks!

**Comment by duz-sg** [comment]
Update, the root cause is some latest change in rabbitmq:3.9, I downgraded it to use rabbitmq:3.8, and this issue has been resolved.
This is a workaround so far, long term wise, some other changes would need to use the latest rabbitmq images.
