### ISSUE TITLE
pydantic.error_wrappers.ValidationError

### ISSUE THREAD

**Issue by yusuke2930** [tiangolo/full-stack-fastapi-postgresql#445]
docker run backned
```
Checking for script in /app/prestart.sh
Running script /app/prestart.sh
Traceback (most recent call last):
  File "/app/app/backend_pre_start.py", line 5, in <module>
    from app.db.session import SessionLocal
  File "/app/app/db/session.py", line 4, in <module>
    from app.core.config import settings
  File "/app/app/core/config.py", line 92, in <module>
    settings = Settings()
  File "pydantic/env_settings.py", line 36, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Settings
SQLALCHEMY_DATABASE_URI
  can only concatenate str (not "NoneType") to str (type=type_error)
```

this code not working?
```
POSTGRES_SERVER: Optional[str] = None
    POSTGRES_USER: Optional[str] = None
    POSTGRES_PASSWORD: Optional[str] = None
    POSTGRES_DB: Optional[str] = None
    SQLALCHEMY_DATABASE_URI: Optional[PostgresDsn] = None

    @validator("SQLALCHEMY_DATABASE_URI", pre=True)
    def assemble_db_connection(cls, v: Optional[str], values: Dict[str, Any]) -> Any:
        if isinstance(v, str):
            return v
        return PostgresDsn.build(
            scheme="postgresql",
            user=values.get("POSTGRES_USER"),
            password=values.get("POSTGRES_PASSWORD"),
            host=values.get("POSTGRES_SERVER"),
            path=f"/{values.get('POSTGRES_DB') or ''}",
        )
```

**Comment by www-gabi** [comment]
By starting it through plain docker it's not going to read your environment variables, that's the main reason of your error.
But you're also starting a single pod, you need the db + other components so you should try with docker-compose from the main folder of the project
If you're on a clean install from the master branch, you should also change the flower image to : mher/flower:0.9.7

**Comment by yusuke2930** [comment]
@www-gabi Thanks! It's resolved.
