### ISSUE TITLE
backend and celeryworker not running

### ISSUE THREAD

**Issue by s33k3rs** [tiangolo/full-stack-fastapi-postgresql#455]
![Tiangolo](https://user-images.githubusercontent.com/11786565/154421633-ca4e2098-3e08-46b7-b454-ecf7c9656ac3.png)
I have installed version 0.5.0 using docker on ubuntu 18.04, but when execute docker with the command _docker-compose up -d_ :
http://localhost/login : can be accessed but can't login
http://localhost/api : show 404 Not Found
http://localhost/docs : show 404 Not Found
http://localhost/redoc : show 404 Not Found
http://localhost:5555 (Flower) : can login but no graphics
http://localhost:5050 (pgAdmin4): can login but no database

**This is logs for backend**
`Checking for script in /app/prestart.sh
Running script /app/prestart.sh
Traceback (most recent call last):
  File "pydantic/env_settings.py", line 192, in pydantic.env_settings.EnvSettingsSource.__call__
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/app/backend_pre_start.py", line 5, in <module>
    from app.db.session import SessionLocal
  File "/app/app/db/session.py", line 4, in <module>
    from app.core.config import settings
  File "/app/app/core/config.py", line 89, in <module>
    settings = Settings()
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 73, in pydantic.env_settings.BaseSettings._build_values
  File "pydantic/env_settings.py", line 195, in pydantic.env_settings.EnvSettingsSource.__call__
pydantic.env_settings.SettingsError: error parsing JSON for "BACKEND_CORS_ORIGINS"
Checking for script in /app/prestart.sh
Running script /app/prestart.sh
Traceback (most recent call last):
  File "pydantic/env_settings.py", line 192, in pydantic.env_settings.EnvSettingsSource.__call__
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/app/backend_pre_start.py", line 5, in <module>
    from app.db.session import SessionLocal
  File "/app/app/db/session.py", line 4, in <module>
    from app.core.config import settings
  File "/app/app/core/config.py", line 89, in <module>
    settings = Settings()
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 73, in pydantic.env_settings.BaseSettings._build_values
  File "pydantic/env_settings.py", line 195, in pydantic.env_settings.EnvSettingsSource.__call__
pydantic.env_settings.SettingsError: error parsing JSON for "BACKEND_CORS_ORIGINS"
Checking for script in /app/prestart.sh
Running script /app/prestart.sh
Traceback (most recent call last):
  File "pydantic/env_settings.py", line 192, in pydantic.env_settings.EnvSettingsSource.__call__
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/app/backend_pre_start.py", line 5, in <module>
    from app.db.session import SessionLocal
  File "/app/app/db/session.py", line 4, in <module>
    from app.core.config import settings
  File "/app/app/core/config.py", line 89, in <module>
    settings = Settings()
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 73, in pydantic.env_settings.BaseSettings._build_values
  File "pydantic/env_settings.py", line 195, in pydantic.env_settings.EnvSettingsSource.__call__
pydantic.env_settings.SettingsError: error parsing JSON for "BACKEND_CORS_ORIGINS"
Checking for script in /app/prestart.sh
Running script /app/prestart.sh
Traceback (most recent call last):
  File "pydantic/env_settings.py", line 192, in pydantic.env_settings.EnvSettingsSource.__call__
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/app/backend_pre_start.py", line 5, in <module>
    from app.db.session import SessionLocal
  File "/app/app/db/session.py", line 4, in <module>
    from app.core.config import settings
  File "/app/app/core/config.py", line 89, in <module>
    settings = Settings()
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 73, in pydantic.env_settings.BaseSettings._build_values
  File "pydantic/env_settings.py", line 195, in pydantic.env_settings.EnvSettingsSource.__call__
pydantic.env_settings.SettingsError: error parsing JSON for "BACKEND_CORS_ORIGINS"
`

**And logs for  celeryworker**
`  File "/app/app/db/session.py", line 4, in <module>
    from app.core.config import settings
  File "/app/app/core/config.py", line 89, in <module>
    settings = Settings()
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 73, in pydantic.env_settings.BaseSettings._build_values
  File "pydantic/env_settings.py", line 195, in pydantic.env_settings.EnvSettingsSource.__call__
pydantic.env_settings.SettingsError: error parsing JSON for "BACKEND_CORS_ORIGINS"
Traceback (most recent call last):
  File "pydantic/env_settings.py", line 192, in pydantic.env_settings.EnvSettingsSource.__call__
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/app/celeryworker_pre_start.py", line 5, in <module>
    from app.db.session import SessionLocal
  File "/app/app/db/session.py", line 4, in <module>
    from app.core.config import settings
  File "/app/app/core/config.py", line 89, in <module>
    settings = Settings()
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 73, in pydantic.env_settings.BaseSettings._build_values
  File "pydantic/env_settings.py", line 195, in pydantic.env_settings.EnvSettingsSource.__call__
pydantic.env_settings.SettingsError: error parsing JSON for "BACKEND_CORS_ORIGINS"
Traceback (most recent call last):
  File "pydantic/env_settings.py", line 192, in pydantic.env_settings.EnvSettingsSource.__call__
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/app/celeryworker_pre_start.py", line 5, in <module>
    from app.db.session import SessionLocal
  File "/app/app/db/session.py", line 4, in <module>
    from app.core.config import settings
  File "/app/app/core/config.py", line 89, in <module>
    settings = Settings()
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 73, in pydantic.env_settings.BaseSettings._build_values
  File "pydantic/env_settings.py", line 195, in pydantic.env_settings.EnvSettingsSource.__call__
pydantic.env_settings.SettingsError: error parsing JSON for "BACKEND_CORS_ORIGINS"
Traceback (most recent call last):
  File "pydantic/env_settings.py", line 192, in pydantic.env_settings.EnvSettingsSource.__call__
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/app/celeryworker_pre_start.py", line 5, in <module>
    from app.db.session import SessionLocal
  File "/app/app/db/session.py", line 4, in <module>
    from app.core.config import settings
  File "/app/app/core/config.py", line 89, in <module>
    settings = Settings()
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 73, in pydantic.env_settings.BaseSettings._build_values
  File "pydantic/env_settings.py", line 195, in pydantic.env_settings.EnvSettingsSource.__call__
pydantic.env_settings.SettingsError: error parsing JSON for "BACKEND_CORS_ORIGINS"
Traceback (most recent call last):
  File "pydantic/env_settings.py", line 192, in pydantic.env_settings.EnvSettingsSource.__call__
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/app/celeryworker_pre_start.py", line 5, in <module>
    from app.db.session import SessionLocal
  File "/app/app/db/session.py", line 4, in <module>
    from app.core.config import settings
  File "/app/app/core/config.py", line 89, in <module>
    settings = Settings()
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/env_settings.py", line 73, in pydantic.env_settings.BaseSettings._build_values
  File "pydantic/env_settings.py", line 195, in pydantic.env_settings.EnvSettingsSource.__call__
pydantic.env_settings.SettingsError: error parsing JSON for "BACKEND_CORS_ORIGINS"
`
How to solve this problems?
Is there a version other than backend:latest and celeryworker:latest ?

**Comment by migoya2020** [comment]
I had ro run the  backend inside the container to make it work.
Read the  README.md  file;
Here is what you need to do;

```console
$ docker-compose up -d
```

and then `exec` inside the running container:

```console
$ docker-compose exec backend bash
```

You should see an output like:

```console
root@7f2607af31c3:/app#
```
Then  Finally,  start the backend with reload session
```/start-reload.sh```

**Comment by s33k3rs** [comment]
![1](https://user-images.githubusercontent.com/11786565/154728056-8d7fe422-0b87-4f84-955e-18098792008a.jpg)
my mistake, have used backend_cors_origins configuration using only http://dev.api.mydomain.com in .env file

change from:
BACKEND_CORS_ORIGINS=http://dev.api.mydomain.com

to:
BACKEND_CORS_ORIGINS=["http://localhost","http://localhost:4200","http://localhost:3000","http://localhost:8080","https://localhost","https://localhost:4200","https://localhost:3000","https://localhost:8080","http://dev.api.mydoman.com","https://stag.api.mydoman.com","https://api.mydoman.com","http://local.dockertoolbox.tiangolo.com","http://localhost.tiangolo.com"]

It's working now
